import {Ajv2020} from "ajv/dist/2020.js";
import {describe, expect, it} from "vitest";
import rulesetSchema from "../../spec/labs/2.0.0/ruleset.schema.json" with {type: "json"};
import worldBranchSchema from "../../spec/labs/4.0.0/world-branch.schema.json" with {type: "json"};
import resultSchema from "../../spec/labs/1.0.0/result.schema.json" with {type: "json"};
import claimSchema from "../../spec/labs/1.0.0/claim.schema.json" with {type: "json"};
import frontierSchema from "../../spec/labs/1.0.0/frontier.schema.json" with {type: "json"};
import supplyScheduleSchema from "../../spec/sai/0.4.0/world-supply-schedule.schema.json" with {type: "json"};
import supplyBlockSchema from "../../spec/sai/0.4.0/world-supply-block.schema.json" with {type: "json"};
import supplyStateSchema from "../../spec/sai/0.4.0/world-supply-state.schema.json" with {type: "json"};
import {REFERENCE_FRONTIER, REFERENCE_RESULTS, REFERENCE_RULESET, createClaimBody, createLabsResult, labsSymmetries, signLabsClaim} from "../../packages/labs/src/index.js";
import {createIdentity} from "../../packages/identity/src/index.js";
import {WORLD_SUPPLY_SCHEDULE_BODY, appendWorldSupplyBlock, createWorldSupplyState, mineWorldSupplyBlock, worldResourceBranch} from "../../packages/kernel/src/index.js";

describe("LABS JSON Schemas", () => {
  const ajv = new Ajv2020({strict: true, formats: {uri: true}});
  it("accepts reference objects and rejects malformed or expanded objects", async () => {
    ajv.addSchema(resultSchema).addSchema(claimSchema).addSchema(supplyBlockSchema);
    const validateRuleset = ajv.compile(rulesetSchema);
    const validateResult = ajv.getSchema(resultSchema.$id)!;
    const validateClaim = ajv.getSchema(claimSchema.$id)!;
    const validateFrontier = ajv.compile(frontierSchema);
    const validateWorldBranch = ajv.compile(worldBranchSchema);
    const validateSupplySchedule = ajv.compile(supplyScheduleSchema);
    const validateSupplyBlock = ajv.getSchema(supplyBlockSchema.$id)!;
    const validateSupplyState = ajv.compile(supplyStateSchema);
    const record = REFERENCE_RESULTS["451"]!;
    const identity = await createIdentity();
    const claim = signLabsClaim(createClaimBody(record.result_id, identity, "reproduction"), identity).signed_claim;
    expect(validateRuleset(REFERENCE_RULESET)).toBe(true);
    expect(validateResult(record.result)).toBe(true);
    expect(validateClaim(claim)).toBe(true);
    expect(validateFrontier(REFERENCE_FRONTIER)).toBe(true);
    const branch = worldResourceBranch(0).labs_branch;
    const baseline = REFERENCE_RULESET.baselines.find((item) => item.length === branch.length)!;
    const candidate_sequence = labsSymmetries(baseline.sequence).find((item) => item.startsWith(branch.sequence_prefix))!;
    const resultObject = createLabsResult(REFERENCE_RULESET, candidate_sequence);
    const signed = signLabsClaim(createClaimBody(resultObject.result_id, identity, "reproduction", [branch.branch_id]), identity);
    const block = mineWorldSupplyBlock(createWorldSupplyState(), branch, {candidate_sequence, ...resultObject, ...signed}, identity.agentId);
    expect(validateWorldBranch(branch)).toBe(true);
    expect(validateSupplySchedule(WORLD_SUPPLY_SCHEDULE_BODY)).toBe(true);
    expect(validateSupplyBlock(block)).toBe(true);
    expect(validateSupplyState(createWorldSupplyState())).toBe(true);
    expect(validateSupplyState(appendWorldSupplyBlock(createWorldSupplyState(), block))).toBe(true);
    expect(validateWorldBranch({...branch, branch_ordinal: -1})).toBe(false);
    expect(validateWorldBranch({...branch, received_at: "now"})).toBe(false);
    expect(validateSupplySchedule({...WORLD_SUPPLY_SCHEDULE_BODY, season_reset: true})).toBe(false);
    expect(validateSupplySchedule({...WORLD_SUPPLY_SCHEDULE_BODY, max_supply: 31_500})).toBe(false);
    expect(validateSupplySchedule({...WORLD_SUPPLY_SCHEDULE_BODY, ruleset_id: `sha256:${"0".repeat(64)}`})).toBe(false);
    expect(validateSupplyBlock({...block, proof_bits: 7})).toBe(false);
    expect(validateSupplyState({...createWorldSupplyState(), received_at: "now"})).toBe(false);
    expect(validateSupplyState({...createWorldSupplyState(), schedule_id: `sha256:${"0".repeat(64)}`})).toBe(false);
    expect(validateRuleset({...REFERENCE_RULESET, resource_cap: 13})).toBe(false);
    expect(validateResult({...record.result, energy: 12625})).toBe(false);
    expect(validateResult({...record.result, server_sequence: 1})).toBe(false);
    expect(validateClaim({...claim, signature: `${claim.signature.slice(1)}!`})).toBe(false);
    expect(validateFrontier({...REFERENCE_FRONTIER, received_at: "now"})).toBe(false);
  });
});
